name: Auto Create Repo JSON

on:
  push:
    paths:
      - 'themes/*.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Show working directory
      run: pwd

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb xorg x11-apps libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxkbcommon0 libxkbcommon-x11-0 libxcb-render0 libxcb-shape0 libxcb-xfixes0 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Set environment variables
      run: |
        export QT_QPA_PLATFORM=offscreen
        
    - name: Check installed Python packages
      run: pip freeze

    - name: Run create_repo.py script
      run: |
        python create_repo.py

    - name: baabarab
      run: |
        echo "Root directory:"
        ls -l
        echo "Preview directory:"
        ls -l preview

    - name: Commit and push repo.json and contents of preview folder
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add repo.json preview/*
        git commit -m "Update repo.json and preview folder contents"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
